### ISSUE TITLE
Unable to close the netconf session using .close() method

### ISSUE THREAD

**Issue by paivinayak187** [jean1880/node-netconf#1] opened 2019-11-15 08:29 UTC
Looks like there is no definition of **close()** function in the library.
I always get router.close() is not a function

**Comment by jean1880** [comment] 2019-11-15 13:04
Hmm, yeah, it looks like when we rebuilt it, since we were never closing by design originally, it never got reworked to close. I've updated the package, and am about to head into the office, if you want to pull down the latest version, it should have close. I kept it to version 1.0, and overwrote the original version, as it should have had close to start with.

**Closed as completed** 2019-11-22 14:54 UTC
